apiVersion: apps/v1
kind: Deployment
metadata:
  name: shell-demo
spec:
  nodeSelector:
    "beta.kubernetes.io/os": linux
  volumes:
  - name: shared-data
    emptyDir: {}
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
  hostNetwork: true
  dnsPolicy: Default