apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx0-deployment
  labels:
    app: nginx0-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx0
  template:
    metadata:
      labels:
        app: nginx0
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux    
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80