apiVersion: apps/v1
kind: Deployment
metadata:
  name: win-helloworld
  labels:
    app: win-helloworld
spec:
  replicas: 1
  template:
    metadata:
      name: win-helloworld
      labels:
        app: win-helloworld
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": windows
      containers:
      - name: win-helloworld
        image: mcr.microsoft.com/dotnet/framework/samples:aspnetapp
        resources:
          limits:
            cpu: 1
            memory: 800M
          requests:
            cpu: .1
            memory: 300M
        ports:
          - containerPort: 80
  selector:
    matchLabels:
      app: win-helloworld
---
apiVersion: v1
kind: Service
metadata:
  name: win-helloworld
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
  selector:
    app: win-helloworld